---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autenticacao
  labels:
    app: autenticacao
    tier: frontend
spec:
  selector:
    matchLabels:
      app: autenticacao
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: autenticacao
        tier: frontend
    spec:
      containers:
        - name: autenticacao
          image: 751916211357.dkr.ecr.us-east-1.amazonaws.com/hackathon-autenticacao
          ports:
            - name: porta-auth
              containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - general
